"use client";

import { useCallback } from "react";
import { netlifyFunctionUrl } from "@/lib/netlify-function-url";
import type { ComparisonResult } from "./step2-analysis-panel";

export type ComparisonClaimMetaSlice = {
  insuredName: string;
  policyNumber: string;
  claimNumber: string;
  dateOfLoss: string;
};

type Props = {
  accessToken: string;
  comparison: ComparisonResult | null;
  claimMeta: ComparisonClaimMetaSlice;
  onBack: () => void;
  onNext: () => void;
  announce: (message: string) => void;
};

const REPORT_DIVIDER = "----------------------------------------";

function formatMoney(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 2,
  }).format(Number.isFinite(n) ? n : 0);
}

function modeLabel(mode: string): string {
  if (mode === "LINE_COMPARE") return "Line-item comparison";
  if (mode === "RECON_VS_CARRIER") return "Reconstructed scope vs carrier";
  return mode || "—";
}

function otherColumnHeaders(mode: string): { item: string; amt: string } {
  if (mode === "LINE_COMPARE") {
    return { item: "Contractor item", amt: "Contractor amount" };
  }
  return { item: "Reconstructed item", amt: "Reconstructed amount" };
}

function deltaClass(delta: number): string {
  if (delta > 0) return "text-emerald-700 font-medium tabular-nums";
  if (delta === 0) return "text-slate-500 tabular-nums";
  return "text-red-600 font-medium tabular-nums";
}

function modeLineForReport(mode: string): string {
  if (mode === "LINE_COMPARE") return "MODE: Line-item Comparison";
  if (mode === "RECON_VS_CARRIER")
    return "MODE: Reconstructed Scope vs Carrier";
  return `MODE: ${mode || "—"}`;
}

function alignClaim(label: string, value: string, w = 22): string {
  const base = label.length <= w ? label.padEnd(w) : `${label} `;
  return `${base}${value}`;
}

function cellPipe(s: string): string {
  return String(s ?? "")
    .replace(/\|/g, "/")
    .replace(/\r?\n/g, " ")
    .trim();
}

/** Plain-text comparison report for PDF/DOCX. */
export function buildComparisonText(
  comparison: ComparisonResult,
  claimMeta: ComparisonClaimMetaSlice
): string {
  const mode = comparison.mode ?? "";
  const lineItems = comparison.lineItems ?? [];
  const header =
    "Trade | Carrier Item | Carrier Amt | Contractor Item | Contractor Amt | Delta | Flag | Reason";
  const rows = lineItems.map((row) =>
    [
      cellPipe(row.trade),
      cellPipe(row.carrierItem),
      formatMoney(row.carrierAmount),
      cellPipe(row.contractorItem),
      formatMoney(row.contractorAmount),
      formatMoney(row.delta),
      row.flagged ? "Yes" : "No",
      cellPipe(row.reason),
    ].join(" | ")
  );

  const parts: string[] = [
    "ESTIMATE REVIEW PRO — COMPARISON REPORT",
    "========================================",
    "",
    "CLAIM IDENTIFICATION",
    alignClaim("Policy Number:", claimMeta.policyNumber || "—"),
    alignClaim("Claim Number:", claimMeta.claimNumber || "—"),
    alignClaim("Insured Name:", claimMeta.insuredName?.trim() || "—"),
    alignClaim("Date of Loss:", claimMeta.dateOfLoss || "—"),
    "",
    REPORT_DIVIDER,
    "",
    modeLineForReport(mode),
    "",
    "LINE ITEMS",
    "",
    header,
    ...rows,
    "",
    REPORT_DIVIDER,
    "",
    "TOTALS",
    alignClaim(
      "Total Carrier:",
      formatMoney(comparison.totalCarrier ?? 0)
    ),
    alignClaim(
      "Total Contractor/Recon:",
      formatMoney(comparison.totalContractor ?? 0)
    ),
    alignClaim("Total Gap:", formatMoney(comparison.totalDelta ?? 0)),
    "",
    REPORT_DIVIDER,
    "",
    "This report was generated by Estimate Review Pro.",
    "This is not legal advice.",
  ];

  return parts.join("\n");
}

export function Step3ComparisonPanel({
  comparison,
  claimMeta,
  onBack,
  onNext,
  announce,
}: Props) {
  const downloadPdf = useCallback(async () => {
    if (!comparison) {
      announce("No comparison data to export.");
      return;
    }
    const text = buildComparisonText(comparison, claimMeta);
    const res = await fetch(netlifyFunctionUrl("generate-pdf"), {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({
        text,
        fileName: "estimate-comparison.pdf",
      }),
    });
    const ct = res.headers.get("content-type") || "";
    if (!res.ok || ct.includes("application/json")) {
      await res.text().catch(() => "");
      announce("PDF download failed. Please try again.");
      return;
    }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "estimate-comparison.pdf";
    a.click();
    URL.revokeObjectURL(url);
    announce("Comparison PDF downloaded.");
  }, [announce, comparison, claimMeta]);

  const downloadWord = useCallback(async () => {
    if (!comparison) {
      announce("No comparison data to export.");
      return;
    }
    const text = buildComparisonText(comparison, claimMeta);
    const res = await fetch(netlifyFunctionUrl("generate-docx"), {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${accessToken}`,
      },
      body: JSON.stringify({
        text,
        fileName: "estimate-comparison.docx",
      }),
    });
    const ct = res.headers.get("content-type") || "";
    if (!res.ok || ct.includes("application/json")) {
      await res.text().catch(() => "");
      announce("Word download failed. Please try again.");
      return;
    }
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "estimate-comparison.docx";
    a.click();
    URL.revokeObjectURL(url);
    announce("Comparison Word document downloaded.");
  }, [accessToken, announce, comparison, claimMeta]);

  const mode = comparison?.mode ?? "";
  const lineItems = comparison?.lineItems ?? [];
  const totalCarrier = comparison?.totalCarrier ?? 0;
  const totalOther = comparison?.totalContractor ?? 0;
  const totalDelta = comparison?.totalDelta ?? 0;

  const { item: otherItemLabel, amt: otherAmtLabel } =
    otherColumnHeaders(mode);

  return (
    <div className="text-[#475569]">
      <h2
        id="erp-step3-heading"
        className="text-2xl font-bold text-[#1E293B]"
      >
        Step 3 — Comparison
      </h2>
      <p id="erp-step3-mode-label" className="mt-2 text-sm text-[#475569]">
        {comparison ? modeLabel(mode) : "—"}
      </p>

      {!comparison && (
        <p className="mt-6 text-sm text-[#475569]">
          No comparison data available
        </p>
      )}

      {comparison && (
        <>
          <div className="mt-6 flex flex-wrap gap-3">
            <button
              id="erp-step3-download-pdf"
              type="button"
              className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-[#1E293B] hover:bg-slate-50"
              onClick={() => void downloadPdf()}
            >
              Download PDF
            </button>
            <button
              id="erp-step3-download-word"
              type="button"
              className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-[#1E293B] hover:bg-slate-50"
              onClick={() => void downloadWord()}
            >
              Download Word
            </button>
          </div>

          <div className="mt-6 overflow-x-auto rounded-lg border border-slate-200 bg-gray-50">
            <table
              id="erp-step3-table"
              className="w-full min-w-[720px] border-collapse bg-gray-50 text-left text-sm text-[#1E293B]"
            >
              <thead>
                <tr className="border-b border-slate-200 bg-gray-50">
                  <th
                    id="erp-step3-colhead-trade"
                    scope="col"
                    className="bg-gray-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    Trade
                  </th>
                  <th
                    id="erp-step3-colhead-carrier-item"
                    scope="col"
                    className="bg-gray-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    Carrier item
                  </th>
                  <th
                    id="erp-step3-colhead-carrier-amount"
                    scope="col"
                    className="border-r border-slate-300 bg-blue-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    Carrier amount
                  </th>
                  <th
                    id="erp-step3-colhead-contractor-or-recon"
                    scope="col"
                    className="bg-gray-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    {otherItemLabel}
                  </th>
                  <th
                    id="erp-step3-colhead-contractor-or-recon-amt"
                    scope="col"
                    className="bg-green-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    {otherAmtLabel}
                  </th>
                  <th
                    id="erp-step3-colhead-delta"
                    scope="col"
                    className="border-r border-slate-300 bg-yellow-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    Delta
                  </th>
                  <th
                    id="erp-step3-colhead-flag"
                    scope="col"
                    className="bg-gray-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    Flag
                  </th>
                  <th
                    id="erp-step3-colhead-reason"
                    scope="col"
                    className="bg-gray-50 px-3 py-3 font-bold text-[#475569]"
                  >
                    Reason
                  </th>
                </tr>
              </thead>
              <tbody>
                {lineItems.map((row, n) => (
                  <tr
                    key={n}
                    id={`erp-step3-row-${n}`}
                    className="border-b border-slate-100 bg-gray-50"
                  >
                    <td
                      id={`erp-step3-cell-${n}-trade`}
                      className="bg-gray-50 px-3 py-2 align-top"
                    >
                      {row.trade}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-carrier-item`}
                      className="bg-gray-50 px-3 py-2 align-top"
                    >
                      {row.carrierItem}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-carrier-amt`}
                      className="border-r border-slate-300 bg-blue-50 px-3 py-2 align-top tabular-nums"
                    >
                      {formatMoney(row.carrierAmount)}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-other-item`}
                      className="bg-gray-50 px-3 py-2 align-top"
                    >
                      {row.contractorItem}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-other-amt`}
                      className="bg-green-50 px-3 py-2 align-top tabular-nums"
                    >
                      {formatMoney(row.contractorAmount)}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-delta`}
                      className={`border-r border-slate-300 bg-yellow-50 px-3 py-2 align-top ${deltaClass(row.delta)}`}
                    >
                      {formatMoney(row.delta)}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-flag`}
                      className="bg-gray-50 px-3 py-2 align-top"
                    >
                      {row.flagged ? (
                        <span className="font-bold text-orange-500" aria-label="Flagged">
                          ●
                        </span>
                      ) : (
                        <span className="text-slate-300" aria-label="Not flagged">
                          –
                        </span>
                      )}
                    </td>
                    <td
                      id={`erp-step3-cell-${n}-reason`}
                      className="bg-gray-50 px-3 py-2 align-top text-[#475569]"
                    >
                      {row.reason}
                    </td>
                  </tr>
                ))}
                <tr className="border-t-2 border-slate-300 bg-gray-100 font-semibold">
                  <td colSpan={2} className="bg-gray-100 px-3 py-3 text-[#1E293B]">
                    Totals
                  </td>
                  <td
                    id="erp-step3-total-carrier"
                    className="border-r border-slate-300 bg-blue-50 px-3 py-3 tabular-nums text-[#1E293B]"
                  >
                    {formatMoney(totalCarrier)}
                  </td>
                  <td className="bg-gray-100 px-3 py-3" aria-hidden />
                  <td
                    id="erp-step3-total-contractor-or-recon"
                    className="bg-green-50 px-3 py-3 tabular-nums text-[#1E293B]"
                  >
                    {formatMoney(totalOther)}
                  </td>
                  <td
                    id="erp-step3-total-delta"
                    className={`border-r border-slate-300 bg-yellow-50 px-3 py-3 tabular-nums ${deltaClass(totalDelta)}`}
                  >
                    {formatMoney(totalDelta)}
                  </td>
                  <td colSpan={2} className="bg-gray-100 px-3 py-3" aria-hidden />
                </tr>
              </tbody>
            </table>
          </div>
        </>
      )}

      <div className="mt-10 flex flex-wrap gap-4 border-t border-slate-200 pt-6">
        <button
          id="erp-step3-back"
          type="button"
          className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-[#475569] hover:bg-slate-50"
          onClick={onBack}
        >
          Back
        </button>
        <button
          id="erp-step3-next"
          type="button"
          className="rounded-lg bg-blue-600 px-6 py-2 text-sm font-semibold text-white hover:bg-blue-700"
          onClick={onNext}
        >
          Continue
        </button>
      </div>
    </div>
  );
}
